### ISSUE TITLE
Add CD GitHub action workflow

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [KMU-Dev/conote#100]
## Tasks
- [x] Move publish docker image, publish helm chart to CD workflow
- [x] Fix publish docker image workflow failed (https://github.com/KMU-Dev/conote/actions/runs/2177443879)
- [x] Add tag support for Sentry release
