### ISSUE TITLE
Migrate to GitHub flow

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [KMU-Dev/conote#65]
Reference: https://docs.github.com/en/get-started/quickstart/github-flow

## Tasks to do
- [x] #66
- [x] Update GitHub Action CI #67 
- [x] Rename branch name from master to main
- [x] Review branch protection rule
