### ISSUE TITLE
Upgrade react from v17 to v18

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [KMU-Dev/conote#92]
## Tasks
- [x] Upgrade react and react-dom package to 18.0.0
- [x] Migrate react to v18
- [ ] Upgrade [apollo-client](https://github.com/apollographql/apollo-client) and add back `React.StrctMode`
- [ ] #94
